### ISSUE TITLE
Problem with s3ql - Import can't integer

### ISSUE THREAD

**Issue by smithpl2000** [s3ql/s3ql#211] opened 2020-10-17 21:52 UTC
I've just compile s3ql on Centos 7 with Python 3.6

Whatever I want to do, s3ql 3.3/3.5 says:

ImportError: cannot import name 'INTEGER'

/usr/local/bin/mount.s3ql --authfile /root/s3qlcredentials.txt swiftks://<mask> /mnt/folder/
Traceback (most recent call last):
  File "/usr/local/bin/mount.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==3.3', 'console_scripts', 'mount.s3ql')())
  File "/usr/local/bin/mount.s3ql", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib64/python3.6/site-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/mount.py", line 18, in <module>
  File "/usr/local/lib64/python3.6/site-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/metadata.py", line 13, in <module>
ImportError: cannot import name 'INTEGER'

**Comment by panslothda** [comment] 2020-10-18 16:03
Hi!

I had the same issue as you.

But when I downgraded setuptools to v47.0 it worked for me. (also on centos)

So following 3 commands in the directory where you unpacked s3ql
pip3 install setuptools==47.0
python3 setup.py build_ext --inplace
python3 setup.py install

(or whichever way of installing you choose in the end)

Got my own solution from this issue: https://github.com/s3ql/s3ql/issues/193
if that doesn't solve your issue please ignore me :)

Maybe this should be added to the installation requirement?

**Comment by Nikratio** [comment] 2020-11-09 10:06
Closed this as dupe of #193

**Closed by Nikratio** 2020-11-09 10:06 UTC
