### ISSUE TITLE
file fsync: TypeError: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by d--j** [s3ql/s3ql#161] opened 2020-04-05 15:15 UTC
When a program like this test program calls [fsync](https://linux.die.net/man/2/fsync), S3QL will crash

```python
#!/usr/bin/env python3

import os

with open('test', 'wb') as f:
	f.write(b'this is a test')
	f.flush()
	os.fsync(f.fileno()) # this will crash S3QL

```

This is the traceback:
```
2020-04-05 17:09:27.981 10721:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/mount.s3ql", line 8, in <module>
    sys.exit(main())
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/s3ql/mount.py", line 131, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/trio/_core/_run.py", line 1783, in run
    raise runner.main_task_outcome.error
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/s3ql/mount.py", line 256, in main_async
    ret = await pyfuse3.main()
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/pyfuse3.pyx", line 727, in main
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/trio/_core/_run.py", line 725, in __aexit__
    raise combined_error_from_nursery
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/internal.pxi", line 253, in _session_loop
  File "src/handlers.pxi", line 530, in fuse_fsync_async
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/s3ql/fs.py", line 1128, in fsync
    await self.cache.flush_local(fh, blockno)
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by Nikratio** [comment] 2020-04-05 15:50
Duplicate of #159 (and already fixed)

**Closed by Nikratio** 2020-04-05 15:50 UTC
Labels: duplicate
