### ISSUE TITLE
Ship a requirements.txt file

### ISSUE THREAD

**Issue by jazeltq** [s3ql/s3ql#51] opened 2018-12-19 03:18 UTC
Hello, can we add one requirements file for this project, then user install will be more fluently.

**Comment by szepeviktor** [comment] 2018-12-19 07:48
This is a very nice idea.

https://github.com/s3ql/s3ql/blob/master/setup.py#L132-L137

Although s3ql is not a published package.

**Comment by Nikratio** [comment] 2018-12-19 10:20
Hmm. I would have thought that this is generated automatically by setup.py when building the release tarball. Do you have a link that defines this requirements file?

**Comment by szepeviktor** [comment] 2018-12-19 10:32
Maybe https://pip.readthedocs.io/en/1.1/requirements.html ?

**Comment by Nikratio** [comment] 2018-12-28 18:48
I also found https://packaging.python.org/discussions/install-requires-vs-requirements/, but it is still not clear to me what there is a need to have both.

That said, I guess having another requirements.txt file wouldn't hurt. If anyone wants to submit a pull request..? :-)

**Comment by stjosh** [comment] 2019-02-28 14:50
In order to avoid consistenty problems, a pragmatic approach might be to just add the following `requirements.txt`:

```
--index-url https://pypi.python.org/simple/
-e .
```

See [this blog post](https://caremad.io/posts/2013/07/setup-vs-requirement/) by  [Donald Stufft](https://github.com/dstufft) (who I'd consider an "authority" on this kind of question ;-) )

Furthermore, I think the requirements specified should also be used in `.travis.yml` instead of specifying them again manually, so the requirements are specified in only one place (which happens to be `setup.py`). I'll try to come up with a PR for this.

**Comment by Nikratio** [comment] 2019-03-24 12:57
stjosh@, any update on a PR?

**Comment by szepeviktor** [comment] 2019-03-24 13:03
@Nikratio The mention!

**Comment by Nikratio** [comment] 2019-03-24 14:36
@stjosh Do you still plan to work on this?

**Comment by stjosh** [comment] 2019-03-24 18:06
I actually do - thought it makes sense to have #92 merged first. But since it‘s merged now, I‘ll follow up on this one!

**Comment by stjosh** [comment] 2019-03-27 15:05
After a few (failing) trials in #98, I came back to researching about the difference of specifying requirements in `requirements.txt` and `setup.py`. After all, I found very nice explanation on StackOverflow: https://stackoverflow.com/a/33685899/4361275

With this in mind, I actually conclude the following:
- It's not really a good idea to try to reference from `setup.py` to `requirements.txt` or vice versa in case of `s3ql` 
- `setup.py` should stay as it is - it defines the required packages for _installing and running_  `s3ql`
- Specification of the modules required to _build and test_ the software are specified in `.travis.yml` - the only change I'd propose here is to explicitly fix the dependency package versions instead of allowing the same ranges as in `setup.py` in order to allow for reproducible builds.

After all, I don't really see a _need_ to have a `requirements.txt` file - the only usage that _might_ make sense: specify the packages and specific versions used for Travis builds, so Travis builds could be reproduced also in any "clean" python environment. In `.travis.yml`, we could then just say `pip install -r requirements.txt` and the contents of `requirements.txt` would look like

```
apsw==3.8.2
defusedxml==0.5.0
...
```

**Comment by szepeviktor** [comment] 2019-03-27 15:54
@stjosh Would you be so kind to look at highly popular pip packages, how they do it?

**Comment by stjosh** [comment] 2019-03-28 15:12
I've strolled through quite a few repos of the top-15 projects on https://pythonwheels.com . I haven't found a single project with a `requirements.txt` file in the repo (except for [colorama](https://github.com/tartley/colorama), but there it's explicitly empty :smile:). There are quite a few projects having `dev-requirements.txt` files - I haven't really found good documentation on what these files are being used for, though.

So, I'll stay with my conclusion/proposals above and will not put any more work into this unless someone (e.g., @Nikratio ) can give me a clear idea on what the `s3ql` project really wants/needs to support in that regard. Simply adding another file containing the same information that is already present elsewhere without a clear use-case does not seem to be a good idea to me.

**Comment by Nikratio** [comment] 2019-10-20 10:34
Looks like there is no clear consensus on a `requirement.txt` being a good idea.

**Closed by Nikratio** 2019-10-20 10:34 UTC
Labels: enhancement
