### ISSUE TITLE
Attempting to mount volume never terminates

### ISSUE THREAD

**Issue by mflage** [s3ql/s3ql#172] opened 2020-05-31 20:37 UTC
When attempting to mount my newly-formatted volume, the process never terminates, but instead hangs at the following:

```
# mount.s3ql --authfile s3qlcredentials.txt swiftks://auth.cloud.ovh.net/DE:ARCHIVE /mnt/container/
Using 2 upload threads.
Autodetected 1048538 file descriptors available for cache entries
Detected Swift features for storage.de.cloud.ovh.net:443: copy via COPY, Bulk delete 1000 keys at a time, maximum meta value length is 255 bytes
WARNING: Ignoring retry-after value of 14388.000 s, using 300.000 s instead
```

The mkfs seems to have completed successfully:

```
~# mkfs.s3ql --authfile s3qlcredentials.txt swiftks://auth.cloud.ovh.net/DE:ARCHIVE
Detected Swift features for storage.de.cloud.ovh.net:443: copy via COPY, Bulk delete 1000 keys at a time, maximum meta value length is 255 bytes
Before using S3QL, make sure to read the user's guide, especially
the 'Important Rules to Avoid Losing Data' section.
Enter encryption password:
Confirm encryption password:
Generating random encryption key...
Creating metadata tables...
Dumping metadata...
Dumping metadata...
..objects..
..blocks..
..inodes..
..inode_blocks..
..symlink_targets..
..names..
..contents..
..ext_attributes..
Compressing and uploading metadata...
Wrote 151 bytes of compressed metadata.
Cycling metadata backups...
Backing up old metadata...
Please store the following master key in a safe location. It allows
decryption of the S3QL file system in case the storage objects holding
this information get corrupted:
---BEGIN MASTER KEY---
XXXXXXXXXXXXXXXX
---END MASTER KEY---
```

This is towards the Cloud Archive service from OVH. I'm running on Ubuntu 20.04 with the s3ql version that's available there (Version: 3.3.2+dfsg-1ubuntu1).

What am I doing wrong? I followed this HOWTO https://docs.ovh.com/gb/en/storage/use_s3ql_to_mount_object_storage_containers/, but I had to omit the "--backend-options domain=default" from the mkfs command, as that yielded an Unauthorized error.

When looking in the control panel for OVH I can see that there are some objects generated inside the archive, so the mkfs has done something.

**Comment by Nikratio** [comment] 2020-06-14 13:09
Thanks for taking the time to report this issue!
 
I'm afraid it's unlikely that someone will look into this anytime soon. There has not been much active development of S3QL for quite some time - for most users it does what they need it to do. If issues are encountered, then they are either fixed by the people who are annoyed by them, or they tend to remain open.

This is just to calibrate expectations. I am grateful that you took the time to report this and make S3QL better. I'll leave this issue open to document the problem and who knows, maybe someone will pick it up after all :-).

**Comment by redneb** [comment] 2020-06-28 18:01
@mflage The cause of your problem is that s3ql does not fully support OVH's Cloud Archive. This service is a cold (or offline) storage solution; every time you make a request to retrieve an object, you have to wait for it to become available. The waiting time can me anything between 0 to 12 hours, although I've noticed that in practice it's commonly 4 hours.

So what is happening here is this: `mkfs.s3ql` works just fine because it never tries to retrieve any object from the backend. `mount.s3ql` on the other hand, has to retrieve one of the metadata objects which causes the long wait time. In fact, if you wait long enough, `mkfs.s3ql` should eventually succeed because OVH will be sending 429 responses with the `retry-after` header which `s3ql` knows how to handle correctly. But having to wait for several hours after every mount it not practical. Also, every time you would read a file from the s3ql volume, you would have to wait for several hours before each block is retrieved from the backend.

It would be great if s3ql supported something like OVH's Cloud Archive, but this would change the scope the project significantly which I don't think is reasonable to expect/request. I have thought about creating a solution outside of s3ql (like an http proxy that would split s3ql's objects in two separate tiers), but that's outside the scope of this ticket and this issue tracker.

> What am I doing wrong? I followed this HOWTO https://docs.ovh.com/gb/en/storage/use_s3ql_to_mount_object_storage_containers/, but I had to omit the "--backend-options domain=default" from the mkfs command, as that yielded an Unauthorized error.

This is probably due to #180.

**Comment by Nikratio** [comment] 2020-07-17 08:14
Closing per previous comment, thanks redneb!

**Closed by Nikratio** 2020-07-17 08:14 UTC
