### ISSUE TITLE
Keystone v3 fails and OVH Swift

### ISSUE THREAD

**Issue by drgrumpy** [s3ql/s3ql#146] opened 2020-02-07 12:21 UTC
Using latest version 3.3.2

This seems similar to #140 
I have been using s3ql with keystone v2 to access ovh object storage for a couple of years without issues. OVH are now going to move keystone v3 only. Accordingly I have added:
--backend-options domain=Default
to my mount command as per documentation to force v3, but it results in failure with following log output (same as #140):

> 2020-02-07 11:40:03.194 1457:MainThread s3ql.mount.determine_threads: Using 2 upload threads.
> 2020-02-07 11:40:03.194 1457:MainThread s3ql.mount.main: Autodetected 4058 file descriptors available for cache entries
> 2020-02-07 11:40:03.281 1457:MainThread s3ql.backends.common.get_ssl_context: Reading default CA certificates.
> 2020-02-07 11:40:03.287 1457:MainThread s3ql.backends.swift._do_request: started with 'GET', '/', None, {'limit': 1}, None, None
> 2020-02-07 11:40:03.288 1457:MainThread s3ql.backends.swift._do_request: no active connection, calling _get_conn()
> 2020-02-07 11:40:03.288 1457:MainThread s3ql.backends.swiftks._get_conn: started
> 2020-02-07 11:40:03.386 1457:MainThread root.excepthook: No permission to access backend.

Note that my backend-login is in the form tenant:user 

ovh have not been helpful so far, their guide for using s3ql does not work for v3

It may be irrelevant but there seems a subtle difference between the code in backends/swiftks.py the 
is different from that suggested by ovh domain:{name vs. domain:{id

> POST /v3/auth/tokens HTTP/1.1
>  Host: auth.cloud.ovh.net
>  Content-Length: <length>
>  Content-Type: application/json
> 
>  {
>      "auth": {
>          "identity": {
>              "methods": [
>                  "password"
>              ],
>              "password": {
>                  "user": {
>                      "name": "<username>",
>                      "domain": {
>                          "name": "Default"
>                      },
>                      "password": "<password>"
>                  }
>              }
>          }
>      }
>  }

Anyone else have it working with ovh and keystone 3 ?

**Comment by dalgwen** [comment] 2020-02-09 09:49
Hello @drgrumpy
I'm in the EXACT same position.
I guess you received some warning email a few days ago, and are trying since then to use the v3 api ;-) . We have until march 24th to find the solution.
If you find something, I hope you will share it here. I will do the same.

**Comment by szepeviktor** [comment] 2020-02-09 13:03
Latest S3QL does support Keystone v3: https://github.com/s3ql/s3ql/pull/117/files

Add `backend-options: domain=Default` to your authinfo2 file.

**Comment by szepeviktor** [comment] 2020-02-09 13:05
@Nikratio I think there is a difference between the S3QL and the `python-keystoneclient` package implementation of Keystone v3.

**Comment by szepeviktor** [comment] 2020-02-09 13:07
Definitely a duplicate of #140

**Comment by szepeviktor** [comment] 2020-02-09 13:35
> subtle difference between the code in backends/swiftks.py the
is different from that suggested by ovh `domain:{ name` vs. `domain:{ id`

In these examples https://docs.openstack.org/api-ref/identity/v3/?expanded=password-authentication-with-unscoped-authorization-detail#password-authentication-with-unscoped-authorization domain has a lowercase `id` and a sentence case `name`.

The Domain object is defined in keystoneclient's source
https://github.com/openstack/python-keystoneclient/blob/526350eaeeadef8c1ca5f80547c01f94342a6653/keystoneclient/v3/domains.py#L20-L29

In our implementation there is only `id`
https://github.com/s3ql/s3ql/blob/d5e85e633885af44545c9e230be3d09ae6073b12/src/s3ql/backends/swiftks.py#L96-L98

OVH suggests `name` only
https://docs.ovh.com/gb/en/storage/pca/dev/#authentication

```
                     "domain": {
                         "name": "Default"
                     },
```

As `id` is the UUID we should send `name` instead #147

**Comment by drgrumpy** [comment] 2020-02-09 13:50
@dalgwen Yes I will share anything I find...

**Closed** 2020-02-09 14:06 UTC

**Comment by szepeviktor** [comment] 2020-02-09 16:30
@Nikratio I've tried with the modification in my PR and even with changing id to name in the scope: https://github.com/s3ql/s3ql/blob/f37734fb55b14daef6acd4a3f7b692944ca459cc/src/s3ql/backends/swiftks.py#L106-L108
Still `root.excepthook: No permission to access backend.`
Please reopen.

**Comment by szepeviktor** [comment] 2020-02-09 16:57
### Solution for OVH

1. the above PR #147 
1. change id to name in scope
1. use `OS_TENANT_ID` instead of `OS_TENANT_NAME`

e.g. in the downloadable `openrc.sh` from OVH

```bash
export OS_TENANT_ID=682cd80314124c06b9928b2094b4af88
export OS_TENANT_NAME="2475152696807800"
```

**Comment by drgrumpy** [comment] 2020-02-10 00:28
This is all a bit obscure to me, is it fixed and working?
What do I need to do to get it working? @szepeviktor do you have it working ?

I can see that the two lines of code have been changed from id to name as I highlighted originally,I changed those two lines and then ran:
python3 setup.py build_ext --inplace
and
sudo python3 setup.py install

And then does this mean that I need to replace TENANT_NAME with TENANT_ID in the authinfo file?

**Comment by drgrumpy** [comment] 2020-02-10 00:34
OK, I just tested and the answer is yes, so for others, what I did, to get it working:

1. Change those two lines in source and rebuild...

2. Use TENANT_ID instead of TENANT_NAME in Authinfo, i.e.:
from:
backend-login: TENANT_NAME: USERNAME
to:
backend-login: TENANT_ID: USERNAME
the id is a lot longer than the name

**Comment by szepeviktor** [comment] 2020-02-10 00:54
Yes!

**Comment by drgrumpy** [comment] 2020-02-10 00:57
Thanks for your help with this @szepeviktor.

**Comment by d--j** [comment] 2020-02-11 17:02
Hi guys,

I'm also on OVH Swift and am switching to Keystone v3 (since they deprecate v2).

Merge request #147 and #148 are breaking changes. If we do want to do this we need to also explicitly mention that in the changelog.

Connecting to OVH's OpenStack Swift via Keystone v3 is possible right now with version 3.3.2 without any patches. Just use `default` instead of `Default` for the domain backend option. As @szepeviktor pointed out, you also need to use the tenant/project ID instead of the tenant name (as in the Keystone v2 case)

`Default` is the default OpenStack domain. It has `Default` as domain name and `default` as domain ID.

I propose reverting #147 and #148 and instead changing the documentation (#150). Thus 
@ejtbrown and anybody using Keystone v3 right now does not need to change anything.

**Comment by szepeviktor** [comment] 2020-02-11 17:08
That sounds good.
