### ISSUE TITLE
ImportError with setuptools 46.4.0+ (cannot import name 'INTEGER')

### ISSUE THREAD

**Issue by belkone** [s3ql/s3ql#193] opened 2020-08-18 08:11 UTC
Hi,

I have a problem executing 'mkfs.s3ql'.
Below is the result of the operation:

```
Traceback (most recent call last):
  File "/usr/local/bin/mkfs.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==3.5.0', 'console_scripts', 'mkfs.s3ql')())
  File "/usr/local/bin/mkfs.s3ql", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/s3ql-3.5.0-py3.7-linux-x86_64.egg/s3ql/mkfs.py", line 15, in <module>
    from .metadata import dump_and_upload_metadata, create_tables
  File "/usr/local/lib/python3.7/dist-packages/s3ql-3.5.0-py3.7-linux-x86_64.egg/s3ql/metadata.py", line 13, in <module>
    from .deltadump import INTEGER, BLOB, dump_table, load_table
ImportError: cannot import name 'INTEGER' from 's3ql.deltadump' (/root/.cache/Python-Eggs/s3ql-3.5.0-py3.7-linux-x86_64.egg-tmp/s3ql/deltadump.cpython-37m-x86_64-linux-gnu.so
```

Possible related: [https://www.mail-archive.com/s3ql@googlegroups.com/msg01901.html](https://www.mail-archive.com/s3ql@googlegroups.com/msg01901.html)

**Comment by r0ps3c** [comment] 2020-08-18 20:29
https://www.mail-archive.com/s3ql@googlegroups.com/msg01912.html suggests there is a dependency on the version of setuptools

**Comment by belkone** [comment] 2020-08-18 20:45
> https://www.mail-archive.com/s3ql@googlegroups.com/msg01912.html suggests there is a dependency on the version of setuptools

thanks, it is! I downgraded setuptools to 46.4.0 and it works like a charm ;)

**Comment by r0ps3c** [comment] 2020-09-17 03:04
For anyone coming across this - https://www.mail-archive.com/s3ql@googlegroups.com/msg01928.html provides some additional detail/recommendations indicating that the build/install might be causing this issue, and recommending the use of wheels.

**Comment by Nikratio** [comment] 2020-11-09 10:09
I suspect the issue is that in the above case, S3QL was installed in a `.egg` file. Maybe setuptools changed to create `.egg` files by default? There is probably an option to install it into directory instead...

**Comment by Nikratio** [comment] 2020-12-29 09:41
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request.

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).

**Closed by Nikratio** 2020-12-29 09:41 UTC
Labels: bug
