### ISSUE TITLE
How to fsck with old version (2.21) on swift OpenStack v3 auth ?

### ISSUE THREAD

**Issue by NikoTesla** [s3ql/s3ql#185] opened 2020-06-26 14:34 UTC
Hello,

i've a container on OVH object Storage and i use s3ql version 2.21. OVH are upgraded to OpenStack v3 but i can't mount with the old client. So i've installed s3ql version 3.3.2 but i've an error message with the s3qladm upgrade :

Detected Swift features for storage.gra.cloud.ovh.net:443: copy via COPY, Bulk delete 1000 keys at a time, maximum meta value length is 255 bytes
Enter file system encryption passphrase:
Using cached metadata.
File system is damaged, need to run fsck before upgrade.
The last S3QL version that supported this file system revision
was 2.26.

If i launch the fsck with the s3ql v3.3.2 ::
ERROR: File system revision needs upgrade (or backend data is corrupted)

Infinite loop :-(

How i can use the fsck of s3ql v2.21 on OpenStack v3 auth ?
Thanks in advance

**Comment by retmas-gh** [comment] 2020-06-26 20:42
Hi,
can't tell you what repercussions might appear doing this as i am not a developer just a hobbyist, but I successfully manually applied these commits:
* https://github.com/s3ql/s3ql/commit/8321b08ae0f2d288b4983e84cbe0a9969e5f4a59
* https://github.com/s3ql/s3ql/commit/1948844c1f9ae31b7380484393d4d1c2ee7e75b3
* https://github.com/s3ql/s3ql/commit/c09df7beeaf9759f1c9f23e47a91eec1efee31d1

to the ubuntu's bionic [2.26](https://packages.ubuntu.com/bionic/s3ql) version sources, then, as per installation guide, ran `python3 setup.py build_ext --inplace` and used these binaries to fsck the filesystem with, i believe:
```
bin/fsck.s3ql --backend-options domain=default --authfile s3qlcredentials.txt swiftks://auth.cloud.ovh.net/.....
```
I was then able to use the new version of `s3qladm` to upgrade the filesystem and finally mount it.
Your milage may vary, especially since your version of 2.21 is older than mine (although the s3qladm error you provided says 2.26).

An additional thing you may need: the `backend-login` first part (before colon) in keystone3 changes from `Project Name` to `Project ID`.

If you do not feel safe to experiment with this you may want to wait for some knowlegable person to help you.

Kind regards.

**Comment by NikoTesla** [comment] 2020-06-29 08:36
hello @retmas-gh ,

thanks but i've this error when i launch the fsck :

```
Traceback (most recent call last):
  File "./fsck.s3ql", line 25, in <module>
    import s3ql.fsck
  File "/root/s3ql/src/s3ql/fsck.py", line 11, in <module>
    from .backends.common import NoSuchObject
  File "/root/s3ql/src/s3ql/backends/__init__.py", line 9, in <module>
    from . import local, s3, gs, s3c, swift, rackspace, swiftks
  File "/root/s3ql/src/s3ql/backends/swift.py", line 33, in <module>
    class Backend(AbstractBackend, metaclass=ABCDocstMeta):
  File "/root/s3ql/src/s3ql/backends/swift.py", line 568, in Backend
    @copy_ancestor_docstring
  File "/root/s3ql/src/s3ql/inherit_docstrings.py", line 47, in _copy_ancestor_docstring
    "exist in superclass" % fn.__name__)
RuntimeError: Can't inherit docstring for has_delete_multi: method does not exist in superclass
```
I've manually applied the commits, and the buil is ok
Do you have an idea ?

**Comment by NikoTesla** [comment] 2020-07-01 09:19
Hello,

In another way, i can export all s3ql_data from the container. But if i try to mount locally, i've this :

```
mount.s3ql  local:///media/toto/ /media/piwigo/
Using 4 upload threads.
Autodetected 1048532 file descriptors available for cache entries
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==2.21', 'console_scripts', 'mount.s3ql')()
  File "/usr/lib/s3ql/s3ql/mount.py", line 120, in main
    options.authfile, options.compress)
  File "/usr/lib/s3ql/s3ql/common.py", line 340, in get_backend_factory
    backend.fetch('s3ql_passphrase')
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 354, in fetch
    return self.perform_read(do_read, key)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 317, in perform_read
    fh = self.open_read(key)
  File "/usr/lib/s3ql/s3ql/backends/local.py", line 83, in open_read
    fh.metadata = _read_meta(fh)
  File "/usr/lib/s3ql/s3ql/backends/local.py", line 254, in _read_meta
    raise CorruptedObjectError('Invalid object header: %r' % buf)
s3ql.backends.common.CorruptedObjectError: Invalid object header: b'\x80\xaen)\xf8\xfd\xf3\x9a\\'
```

**Comment by d--j** [comment] 2020-07-10 13:51
> In another way, i can export all s3ql_data from the container. [...]

Do not do that. You need to use https://www.rath.org/s3ql-docs/contrib.html#clone-fs-py to copy a file system from one backend to another. Just copying the "files" you are missing vital metadata (that is saved differently on "local" backends so copying the files 1:1 will never work)

> `RuntimeError: Can't inherit docstring for has_delete_multi: method does not exist in superclass`

Looks like you did something wrong applying the patches. The method `has_delete_multi` is old and should be there.

Maybe @retmas-gh can give you his working patched version of S3QL. His solution is your only option: Getting an old version of S3QL to work with Keystone v3. 

You got a ton of emails from OVH warning you that you have to migrate (I got them, too). Next time you get these: Act on them before it is too late!

Since this is not a bug of S3QL, please close this issue and move any further conversation over to the [mailing list](http://groups.google.com/group/s3ql).

**Closed** 2020-07-17 08:10 UTC
