### ISSUE TITLE
open() ignores flags (in particular O_TRUNC)

### ISSUE THREAD

**Issue by r0ps3c** [s3ql/s3ql#182] opened 2020-06-24 12:42 UTC
With s3ql-3.4.1 and pyfuse3-1.3.1 on alpine linux, I am seeing basic data and metadata issues and am unsure what could be going on:

```
/ # mount.s3ql s3://us-west-2/XXXXXXXXX/test/ /mnt
Using 10 upload threads.
Autodetected 1048514 file descriptors available for cache entries
Using cached metadata.
Setting cache size to 148082 MB
Mounting s3://us-west-2/XXXXXXXXX/test/ at /mnt...
/ # mkdir /mnt/dir.1
/ # dd if=/dev/urandom of=/mnt/dir.1/afile bs=1M count=13
13+0 records in
13+0 records out
13631488 bytes (14 MB, 13 MiB) copied, 0.179135 s, 76.1 MB/s
/ # cp -aR /mnt/dir.1 /mnt/dir.2
/ # dd if=/dev/urandom of=/mnt/dir.2/afile bs=1k count=7
7+0 records in
7+0 records out
7168 bytes (7.2 kB, 7.0 KiB) copied, 0.00152389 s, 4.7 MB/s
/ # ls -l /mnt/dir.?/afile; md5sum /mnt/dir.?/afile
-rw-r--r-- 1 root root 13631488 Jun 24 12:32 /mnt/dir.1/afile
-rw-r--r-- 1 root root     7168 Jun 24 12:32 /mnt/dir.2/afile
571c062ebcc6d18a99b1f6e36e89946c  /mnt/dir.1/afile
67043f0760ce941a50d33dc23b9d9bfe  /mnt/dir.2/afile
/ # umount.s3ql mnt && fsck.s3ql --force s3://us-west-2/XXXXXXXXX/t
est/
Starting fsck of s3://us-west-2/XXXXXXXXX/test/
Using cached metadata.
File system seems clean, checking anyway.
Checking DB integrity...
Creating temporary extra indices...
Checking lost+found...
Checking names (refcounts)...
Checking contents (names)...
Checking contents (inodes)...
Checking contents (parent inodes)...
Checking objects (reference counts)...
Checking objects (backend)...
..processed 0 objects so far..
Checking objects (sizes)...
Checking blocks (referenced objects)...
Checking blocks (refcounts)...
Checking blocks (checksums)...
Checking inode-block mapping (blocks)...
Checking inode-block mapping (inodes)...
Checking inodes (refcounts)...
Checking inodes (sizes)...
Checking extended attributes (names)...
Checking extended attributes (inodes)...
Checking symlinks (inodes)...
Checking directory reachability...
Checking unix conventions...
Checking referential integrity...
Dropping temporary indices...
Dumping metadata...
..objects..
..blocks..
..inodes..
..inode_blocks..
..symlink_targets..
..names..
..contents..
..ext_attributes..
Compressing and uploading metadata...
Wrote 545 bytes of compressed metadata.
Cycling metadata backups...
Backing up old metadata...
Cleaning up local metadata...
Completed fsck of s3://us-west-2/XXXXXXXXX/test/
/ # mount.s3ql s3://us-west-2/XXXXXXXXX/test/ /mnt
Using 10 upload threads.
Autodetected 1048514 file descriptors available for cache entries
Using cached metadata.
Setting cache size to 148082 MB
Mounting s3://us-west-2/XXXXXXXXX/test/ at /mnt...
/ # ls -l /mnt/dir.?/afile; md5sum /mnt/dir.?/afile
-rw-r--r-- 1 root root 13631488 Jun 24 12:32 /mnt/dir.1/afile
-rw-r--r-- 1 root root 13631488 Jun 24 12:32 /mnt/dir.2/afile
571c062ebcc6d18a99b1f6e36e89946c  /mnt/dir.1/afile
ff00a560aebb052370bed9768a53a939  /mnt/dir.2/afile
/ # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.0
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

Taking a quick look at the test suite I think this kind of thing should already be caught, so wondering what I'm missing?

**Comment by d--j** [comment] 2020-07-10 14:11
Assuming your file system has the default max block size of 10MiB it looks like the second block of `/mnt/dir2/afile` that you were pruning (by overwriting with fewer than 10MiB) is back again after the fsck.

Please use
`/ # dd if=/dev/urandom of=/mnt/dir.2/afile bs=1M count=12`
instead of
`/ # dd if=/dev/urandom of=/mnt/dir.2/afile bs=1k count=7`

If I am right, this will not change the MD5sum before and after fsck (since the number of blocks did not change)

Can you also try using [s3qlcp](https://www.rath.org/s3ql-docs/man/cp.html) instead of `cp -aR`? (Should not make any difference but just for completeness)

**Comment by r0ps3c** [comment] 2020-07-16 13:00
Unfortunately this does not seem to be the case. I've retried (with a newly-made filesystem), and included the above (modified dd) as well as an additional s3qlcp step:

```
/ # mkfs.s3ql s3://us-west-2/XXXXXXX/test2/
...
/ # mount.s3ql s3://us-west-2/XXXXXXX/test2/ /mnt
...
/ # mkdir /mnt/dir.1
/ # dd if=/dev/urandom of=/mnt/dir.1/afile bs=1M count=13
13+0 records in
13+0 records out
/ # cp -aR /mnt/dir.1 /mnt/dir.2
/ # dd if=/dev/urandom of=/mnt/dir.2/afile bs=1M count=12
12+0 records in
12+0 records out
/ # ls -l /mnt/dir.?/afile; md5sum /mnt/dir.?/afile
-rw-r--r--    1 root     root      13631488 Jul 16 12:39 /mnt/dir.1/afile
-rw-r--r--    1 root     root      12582912 Jul 16 12:39 /mnt/dir.2/afile
9ec0176c6cf6627cb232fc99f416598c  /mnt/dir.1/afile
8db4eaa38613cff3c5e96d8ac640ef88  /mnt/dir.2/afile
/ # umount.s3ql mnt && fsck.s3ql --force s3://us-west-2/XXXXXXX/test2/
Starting fsck of s3://us-west-2/XXXXXXX/test2/
...
Completed fsck of s3://us-west-2/XXXXXXX/test2/
/ # mount.s3ql s3://us-west-2/XXXXXXX/test2/ /mnt
...
/ # ls -l /mnt/dir.?/afile; md5sum /mnt/dir.?/afile
-rw-r--r--    1 root     root      13631488 Jul 16 12:39 /mnt/dir.1/afile
-rw-r--r--    1 root     root      13631488 Jul 16 12:39 /mnt/dir.2/afile
9ec0176c6cf6627cb232fc99f416598c  /mnt/dir.1/afile
9143c003155954d9b6549d70939f1820  /mnt/dir.2/afile
/ # s3qlcp /mnt/dir.1 /mnt/dir.3
/ # dd if=/dev/urandom of=/mnt/dir.3/afile bs=1M count=12
12+0 records in
12+0 records out
/ # ls -l /mnt/dir.?/afile; md5sum /mnt/dir.?/afile
-rw-r--r--    1 root     root      13631488 Jul 16 12:39 /mnt/dir.1/afile
-rw-r--r--    1 root     root      13631488 Jul 16 12:39 /mnt/dir.2/afile
-rw-r--r--    1 root     root      12582912 Jul 16 12:54 /mnt/dir.3/afile
9ec0176c6cf6627cb232fc99f416598c  /mnt/dir.1/afile
9143c003155954d9b6549d70939f1820  /mnt/dir.2/afile
9d63f3646a05b7306fa3563787905a55  /mnt/dir.3/afile
/ # umount.s3ql mnt && fsck.s3ql --force s3://us-west-2/XXXXXXX/test2/
Starting fsck of s3://us-west-2/XXXXXXX/test2/
...
Completed fsck of s3://us-west-2/XXXXXXX/test2/
/ # mount.s3ql s3://us-west-2/XXXXXXX/test2/ /mnt
...
/ # ls -l /mnt/dir.?/afile; md5sum /mnt/dir.?/afile
-rw-r--r--    1 root     root      13631488 Jul 16 12:39 /mnt/dir.1/afile
-rw-r--r--    1 root     root      13631488 Jul 16 12:39 /mnt/dir.2/afile
-rw-r--r--    1 root     root      13631488 Jul 16 12:54 /mnt/dir.3/afile
9ec0176c6cf6627cb232fc99f416598c  /mnt/dir.1/afile
9143c003155954d9b6549d70939f1820  /mnt/dir.2/afile
0a823802ab939621973ae9fb5e61ae37  /mnt/dir.3/afile
```

**Comment by d--j** [comment] 2020-07-17 00:45
I am kinda lost. @Nikratio this looks like a serious problem, could you have a look at it?

This is a boiled down version of the problem:
(see the changed size and MD5 after a re-mount)

```bash
$ mkdir /tmp/s3ql-test
$ mkfs.s3ql --plain local:///tmp/s3ql-test/ 
[...]
$ mount.s3ql --compress none local:///tmp/s3ql-test/ /mnt
[...]
$ mkdir /mnt/dir.1
$ dd if=/dev/urandom of=/mnt/dir.1/afile bs=1M count=2
2+0 records in
2+0 records out
2097152 bytes (2.1 MB, 2.0 MiB) copied, 0.286873 s, 7.3 MB/s
$ cp -aR /mnt/dir.1 /mnt/dir.2
$ dd if=/dev/urandom of=/mnt/dir.2/afile bs=1M count=1
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.0107266 s, 97.8 MB/s
$ ls -l /mnt/dir.?/afile; md5sum /mnt/dir.?/afile
-rw-r--r-- 1 root root 2097152 Jul 17 02:20 /mnt/dir.1/afile
-rw-r--r-- 1 root root 1048576 Jul 17 02:20 /mnt/dir.2/afile
2dfdabc07b9762a1f5bd7103eaa5888b  /mnt/dir.1/afile
314aee92d9d3ae07bd3fbec83461079d  /mnt/dir.2/afile
$ umount.s3ql /mnt
$ mount.s3ql --compress none local:///tmp/s3ql-test/ /mnt
[...]
$ ls -l /mnt/dir.?/afile; md5sum /mnt/dir.?/afile
-rw-r--r-- 1 root root 2097152 Jul 17 02:20 /mnt/dir.1/afile
-rw-r--r-- 1 root root 2097152 Jul 17 02:20 /mnt/dir.2/afile
2dfdabc07b9762a1f5bd7103eaa5888b  /mnt/dir.1/afile
fbcf0c1008006a9f261d21e0aff983c7  /mnt/dir.2/afile
$ umount.s3ql /mnt
$ rm -rf /tmp/s3ql-test
```

This is the database after the second umount:

```sql
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE objects (
        id        INTEGER PRIMARY KEY AUTOINCREMENT,
        refcount  INT NOT NULL,
        size      INT NOT NULL
    );
INSERT INTO "objects" VALUES(1,1,2097250);
INSERT INTO "objects" VALUES(2,1,2097250);
CREATE TABLE blocks (
        id        INTEGER PRIMARY KEY,
        hash      BLOB(32) UNIQUE,
        refcount  INT,
        size      INT NOT NULL,
        obj_id    INTEGER NOT NULL REFERENCES objects(id)
    );
INSERT INTO "blocks" VALUES(1,X'20F5EB9CCA88CD241DA8580F07A4D8781382A11EA8850049EF757B828C01BBEE',1,2097152,1);
INSERT INTO "blocks" VALUES(2,X'30C82CE4B09905F29871D190E39EFDE064E3F86CA72D6787B527D514B9CC20D2',1,2097152,2);
CREATE TABLE inodes (
        -- id has to specified *exactly* as follows to become
        -- an alias for the rowid.
        id        INTEGER PRIMARY KEY AUTOINCREMENT,
        uid       INT NOT NULL,
        gid       INT NOT NULL,
        mode      INT NOT NULL,
        mtime_ns  INT NOT NULL,
        atime_ns  INT NOT NULL,
        ctime_ns  INT NOT NULL,
        refcount  INT NOT NULL,
        size      INT NOT NULL DEFAULT 0,
        rdev      INT NOT NULL DEFAULT 0,
        locked    BOOLEAN NOT NULL DEFAULT 0
    );
INSERT INTO "inodes" VALUES(1,0,0,16877,1594945255544912896,1594945263321638144,1594945255544912896,1,0,0,0);
INSERT INTO "inodes" VALUES(2,0,0,33152,1594945224862707200,1594945224862707200,1594945224862707200,42,0,0,0);
INSERT INTO "inodes" VALUES(3,0,0,16832,1594945224862707200,1594945224862707200,1594945224862707200,1,0,0,0);
INSERT INTO "inodes" VALUES(4,0,0,16877,1594945252280726272,1594945255545500672,1594945252280726272,1,0,0,0);
INSERT INTO "inodes" VALUES(5,0,0,33188,1594945252567609600,1594945255560778240,1594945252567609600,1,2097152,0,0);
INSERT INTO "inodes" VALUES(6,0,0,16877,1594945252280726272,1594945236174725632,1594945255564996864,1,0,0,0);
INSERT INTO "inodes" VALUES(7,0,0,33188,1594945259700294400,1594945263336668416,1594945259700294400,1,2097152,0,0);
CREATE TABLE inode_blocks (
        inode     INTEGER NOT NULL REFERENCES inodes(id),
        blockno   INT NOT NULL,
        block_id    INTEGER NOT NULL REFERENCES blocks(id),
        PRIMARY KEY (inode, blockno)
    );
INSERT INTO "inode_blocks" VALUES(5,0,1);
INSERT INTO "inode_blocks" VALUES(7,0,2);
CREATE TABLE symlink_targets (
        inode     INTEGER PRIMARY KEY REFERENCES inodes(id),
        target    BLOB NOT NULL
    );
CREATE TABLE names (
        id     INTEGER PRIMARY KEY,
        name   BLOB NOT NULL,
        refcount  INT NOT NULL,
        UNIQUE (name)
    );
INSERT INTO "names" VALUES(1,X'6C6F73742B666F756E64',1);
INSERT INTO "names" VALUES(2,X'6469722E31',1);
INSERT INTO "names" VALUES(3,X'6166696C65',2);
INSERT INTO "names" VALUES(4,X'6469722E32',1);
CREATE TABLE contents (
        rowid     INTEGER PRIMARY KEY AUTOINCREMENT,
        name_id   INT NOT NULL REFERENCES names(id),
        inode     INT NOT NULL REFERENCES inodes(id),
        parent_inode INT NOT NULL REFERENCES inodes(id),

        UNIQUE (parent_inode, name_id)
    );
INSERT INTO "contents" VALUES(1,1,3,1);
INSERT INTO "contents" VALUES(2,2,4,1);
INSERT INTO "contents" VALUES(3,3,5,4);
INSERT INTO "contents" VALUES(4,4,6,1);
INSERT INTO "contents" VALUES(5,3,7,6);
CREATE TABLE ext_attributes (
        inode     INTEGER NOT NULL REFERENCES inodes(id),
        name_id   INTEGER NOT NULL REFERENCES names(id),
        value     BLOB NOT NULL,

        PRIMARY KEY (inode, name_id)
    );
ANALYZE sqlite_master;
INSERT INTO "sqlite_stat1" VALUES('objects',NULL,'2');
INSERT INTO "sqlite_stat1" VALUES('blocks','sqlite_autoindex_blocks_1','2 1');
INSERT INTO "sqlite_stat1" VALUES('inodes',NULL,'7');
INSERT INTO "sqlite_stat1" VALUES('inode_blocks','sqlite_autoindex_inode_blocks_1','2 1 1');
INSERT INTO "sqlite_stat1" VALUES('names','sqlite_autoindex_names_1','4 1');
INSERT INTO "sqlite_stat1" VALUES('contents','sqlite_autoindex_contents_1','5 2 1');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('inodes',7);
INSERT INTO "sqlite_sequence" VALUES('contents',5);
INSERT INTO "sqlite_sequence" VALUES('objects',2);
CREATE VIEW contents_v AS
    SELECT * FROM contents JOIN names ON names.id = name_id;
CREATE VIEW ext_attributes_v AS
    SELECT * FROM ext_attributes JOIN names ON names.id = name_id;
COMMIT;
```


This is working (overwriting the second file with exactly the same size):
```bash
$ mkdir /tmp/s3ql-test
$ mkfs.s3ql --plain local:///tmp/s3ql-test/ 
[...]
$ mount.s3ql --compress none local:///tmp/s3ql-test/ /mnt
[...]
$ mkdir /mnt/dir.1
$ dd if=/dev/urandom of=/mnt/dir.1/afile bs=1M count=2
2+0 records in
2+0 records out
2097152 bytes (2.1 MB, 2.0 MiB) copied, 0.285107 s, 7.4 MB/s
$ cp -aR /mnt/dir.1 /mnt/dir.2
$ dd if=/dev/urandom of=/mnt/dir.2/afile bs=1M count=2
2+0 records in
2+0 records out
2097152 bytes (2.1 MB, 2.0 MiB) copied, 0.0204989 s, 102 MB/s
$ ls -l /mnt/dir.?/afile; md5sum /mnt/dir.?/afile
-rw-r--r-- 1 root root 2097152 Jul 17 02:30 /mnt/dir.1/afile
-rw-r--r-- 1 root root 2097152 Jul 17 02:30 /mnt/dir.2/afile
70a4d24603ee784bbbbdd92452cae2c9  /mnt/dir.1/afile
eee08c4947c2b60488df58d684e95c6a  /mnt/dir.2/afile
$ umount.s3ql /mnt
$ mount.s3ql --compress none local:///tmp/s3ql-test/ /mnt
Using 2 upload threads.
Autodetected 1048538 file descriptors available for cache entries
Using cached metadata.
Setting cache size to 5910 MB
Mounting local:///tmp/s3ql-test/ at /mnt...
$ ls -l /mnt/dir.?/afile; md5sum /mnt/dir.?/afile
-rw-r--r-- 1 root root 2097152 Jul 17 02:30 /mnt/dir.1/afile
-rw-r--r-- 1 root root 2097152 Jul 17 02:30 /mnt/dir.2/afile
70a4d24603ee784bbbbdd92452cae2c9  /mnt/dir.1/afile
eee08c4947c2b60488df58d684e95c6a  /mnt/dir.2/afile
$ umount.s3ql /mnt
```




<details>
<summary>Versions</summary>
<p>lsb_release -a</p>
<pre>
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
</pre>
<p>dpkg -l | fgrep fuse3</p>
<pre>
ii  fuse3                                       3.9.2-1~xenial                              amd64        Filesystem in Userspace (3.x version)
ii  libfuse3-3:amd64                            3.9.2-1~xenial                              amd64        Filesystem in Userspace (library) (3.x version)
</pre>
<p>pip list</p>
<pre>
Package              Version
-------------------- -----------
apsw                 3.9.2.post1
async-generator      1.10
atomicwrites         1.4.0
attrs                19.3.0
cachetools           4.1.1
certifi              2020.6.20
cffi                 1.14.0
chardet              3.0.4
cryptography         2.8
defusedxml           0.6.0
dugong               3.7.5
google-auth          1.19.0
google-auth-oauthlib 0.4.1
idna                 2.10
importlib-metadata   1.7.0
more-itertools       8.4.0
oauthlib             3.1.0
outcome              1.0.1
packaging            20.4
pip                  20.1.1
pluggy               0.13.1
py                   1.9.0
pyasn1               0.4.8
pyasn1-modules       0.2.8
pycparser            2.20
pyfuse3              3.1.0
pyparsing            2.4.7
pytest               4.6.5
pytest-trio          0.6.0
requests             2.24.0
requests-oauthlib    1.3.0
rsa                  4.6
s3ql                 3.5.0
setuptools           47.1.0
six                  1.15.0
sniffio              1.1.0
sortedcontainers     2.2.2
systemd              231
trio                 0.16.0
urllib3              1.25.9
wcwidth              0.2.5
wheel                0.34.2
zipp                 3.1.0
</pre>
</details>

**Comment by Nikratio** [comment] 2020-07-17 08:22
Yeah, this looks odd. I'll take a look.

**Comment by Nikratio** [comment] 2020-07-17 12:17
My guess is that for some reason the truncation does not make it into the SQLite DB (but is cached in either kernel or S3QL). So after unmount, the file is back to its original size and the resulting "gap" (since the data was removed) is implicitly filled with zeros (thus the changed MD5).

**Comment by Nikratio** [comment] 2020-07-17 12:40
...but it turns out I am wrong. The metadata changes are persisted (note the correct timestamps on the second mount). Rather, it seems as if truncation is ignored:

```
+ dd if=/usr/share/dict/ngerman of=testdata bs=1M count=2
2+0 records in
2+0 records out
2097152 bytes (2.1 MB, 2.0 MiB) copied, 0.00350978 s, 598 MB/s
+ cp -a testdata testdata2
+ cp -a testdata testdata3
+ dd if=/usr/share/dict/ngerman of=testdata2 bs=1M count=1 skip=3
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00101659 s, 1.0 GB/s
+ dd if=/usr/share/dict/ngerman of=testdata3 bs=1M count=1 skip=3 conv=notrunc
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.000491733 s, 2.1 GB/s
+ echo 'Expected MD5 sums:'
Expected MD5 sums:
+ md5sum testdata testdata2 testdata3
f41b58a8abb7982663c6a5c72d6f1047  testdata
bf87dc6ef01b3c650d70560a96e79528  testdata2
74e9951b256490deff1aba3be97fa4a8  testdata3
+ mkdir bucket
+ mkfs.s3ql --quiet --plain local://bucket
+ mount.s3ql --quiet local://bucket mnt
+ cp -a testdata mnt/
+ cp -a testdata mnt/testdata2
+ dd if=testdata2 of=mnt/testdata2 bs=1M count=1
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00284744 s, 368 MB/s
+ echo 'First iteration:'
First iteration:
+ ls -l mnt/testdata mnt/testdata2
-rw-rw-r-- 1 nikratio nikratio 2097152 Jul 17 13:40 mnt/testdata
-rw-rw-r-- 1 nikratio nikratio 1048576 Jul 17 13:40 mnt/testdata2
+ md5sum mnt/testdata mnt/testdata2
f41b58a8abb7982663c6a5c72d6f1047  mnt/testdata
bf87dc6ef01b3c650d70560a96e79528  mnt/testdata2
+ umount.s3ql mnt
+ mount.s3ql --quiet local://bucket mnt
+ echo 'After unmount:'
After unmount:
+ ls -l mnt/testdata mnt/testdata2
-rw-rw-r-- 1 nikratio nikratio 2097152 Jul 17 13:40 mnt/testdata
-rw-rw-r-- 1 nikratio nikratio 2097152 Jul 17 13:40 mnt/testdata2
+ md5sum mnt/testdata mnt/testdata2
f41b58a8abb7982663c6a5c72d6f1047  mnt/testdata
74e9951b256490deff1aba3be97fa4a8  mnt/testdata2
+ umount.s3ql mnt/
```

**Comment by Nikratio** [comment] 2020-07-17 12:42
...and indeed, it turns out that S3QL does not (and has never supported) the O_TRUNC flag to open() that is used by `dd`.

**Comment by Nikratio** [comment] 2020-07-17 12:48
I've committed a quick fix that causes `dd` to abort with an error instead of silently doing the wrong thing. It should be straightforward to instead truncate the file as intended, but at the moment I don't have the time for that.

**Closed** 2020-09-16 07:55 UTC
Labels: bug
