### ISSUE TITLE
S3QL is closing once a day (OpenStack auth token seems to have expired)

### ISSUE THREAD

**Issue by scysys** [s3ql/s3ql#188] opened 2020-07-16 07:56 UTC
S3QL is closing once a day. I using Version 3.4.1. Using Swift with OVH.
It seems that this version has problems with an expired auth token?

Before i was using version 2.x. On this Version i never had those problems.

Im unsure if this was the problem. I using the same version on another part. There was the same problem, but not each day. There it was once a Week.

The last Logs in mount.log

```
2020-07-14 08:49:22.054 4082:MainThread s3ql.mount.run: Dumping metadata...
2020-07-14 08:49:22.056 4082:MainThread s3ql.metadata.dump_metadata: ..objects..
2020-07-14 08:49:22.166 4082:MainThread s3ql.metadata.dump_metadata: ..blocks..
2020-07-14 08:49:22.349 4082:MainThread s3ql.metadata.dump_metadata: ..inodes..
2020-07-14 08:49:24.520 4082:MainThread s3ql.metadata.dump_metadata: ..inode_blocks..
2020-07-14 08:49:25.019 4082:MainThread s3ql.metadata.dump_metadata: ..symlink_targets..
2020-07-14 08:49:25.021 4082:MainThread s3ql.metadata.dump_metadata: ..names..
2020-07-14 08:49:25.243 4082:MainThread s3ql.metadata.dump_metadata: ..contents..
2020-07-14 08:49:27.105 4082:MainThread s3ql.metadata.dump_metadata: ..ext_attributes..
2020-07-14 08:49:27.663 4082:Trio worker thread 2529 s3ql.metadata.upload_metadata: Compressing and uploading metadata...
2020-07-14 08:49:28.339 4082:Thread-8 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-14 08:49:37.989 4082:Trio worker thread 2529 s3ql.metadata.upload_metadata: Wrote 27.6 MiB of compressed metadata.
2020-07-14 08:49:37.989 4082:Trio worker thread 2529 s3ql.metadata.upload_metadata: Cycling metadata backups...
2020-07-14 08:49:37.989 4082:Trio worker thread 2529 s3ql.metadata.cycle_metadata: Backing up old metadata...
2020-07-14 08:51:32.809 4082:Thread-1 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-14 09:00:28.879 4082:Trio worker thread 2551 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-14 09:00:31.704 4082:Thread-4 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-14 09:00:31.752 4082:Thread-5 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-14 09:01:28.203 4082:Thread-6 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-14 09:01:28.304 4082:Thread-3 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-14 09:01:28.334 4082:Thread-5 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-14 10:21:28.909 4082:Thread-7 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-15 08:49:31.928 4082:Thread-3 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-15 08:49:47.453 4082:MainThread s3ql.mount.run: Dumping metadata...
2020-07-15 08:49:47.454 4082:MainThread s3ql.metadata.dump_metadata: ..objects..
2020-07-15 08:49:47.553 4082:MainThread s3ql.metadata.dump_metadata: ..blocks..
2020-07-15 08:49:47.747 4082:MainThread s3ql.metadata.dump_metadata: ..inodes..
2020-07-15 08:49:50.081 4082:MainThread s3ql.metadata.dump_metadata: ..inode_blocks..
2020-07-15 08:49:50.686 4082:MainThread s3ql.metadata.dump_metadata: ..symlink_targets..
2020-07-15 08:49:50.687 4082:MainThread s3ql.metadata.dump_metadata: ..names..
2020-07-15 08:49:50.910 4082:MainThread s3ql.metadata.dump_metadata: ..contents..
2020-07-15 08:49:52.854 4082:MainThread s3ql.metadata.dump_metadata: ..ext_attributes..
2020-07-15 08:49:53.227 4082:Trio worker thread 5027 s3ql.metadata.upload_metadata: Compressing and uploading metadata...
2020-07-15 08:50:04.403 4082:Trio worker thread 5027 s3ql.metadata.upload_metadata: Wrote 30.0 MiB of compressed metadata.
2020-07-15 08:50:04.403 4082:Trio worker thread 5027 s3ql.metadata.upload_metadata: Cycling metadata backups...
2020-07-15 08:50:04.403 4082:Trio worker thread 5027 s3ql.metadata.cycle_metadata: Backing up old metadata...
2020-07-15 08:51:34.343 4082:Thread-2 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-15 09:00:34.139 4082:Thread-5 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-15 09:00:34.322 4082:Thread-8 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-15 09:01:38.223 4082:Thread-4 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-15 09:03:29.900 4082:Thread-8 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-15 09:04:29.482 4082:Thread-1 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
2020-07-15 10:33:36.276 4082:Thread-2 s3ql.backends.swift._do_authentication_expired: OpenStack auth token seems to have expired, requesting new one.
```

**Comment by Nikratio** [comment] 2020-07-17 08:10
Thanks for taking the time to report this issue!
 
I'm afraid it's unlikely that someone will look into this anytime soon. There has not been much active development of S3QL for quite some time - for most users it does what they need it to do. If issues are encountered, then they are either fixed by the people who are annoyed by them, or they tend to remain open.

This is just to calibrate expectations. I am grateful that you took the time to report this and make S3QL better. I'll leave this issue open to document the problem and who knows, maybe someone will pick it up after all :-).

**Comment by scysys** [comment] 2020-07-17 15:16
I understand. For now i switched to another protocol. But it would be great when someone can look into this for swift.
I personaly cant help with python :(

**Comment by Nikratio** [comment] 2020-11-09 10:11
@d--j Might you have any ideas here? Did the handing of the authentication token in the Swift backend change?

**Comment by Nikratio** [comment] 2020-11-09 10:12
@scysys Could you clarify what you mean by "S3QL is closing"? In the above log, it looks like are no problems at all, S3QL is shutting down gracefully in response to an unmount request.

**Comment by d--j** [comment] 2020-11-09 14:31
I got this (or something very similar), too. S3QL quit unclean without a traceback. This only happens very very sporadically for me, tho. (let's say once in 3 month for one out of 6 actively, permanently used S3QL file systems)

As far as I remember the "OpenStack auth token seems to have expired, requesting new one." messages were quite some time before the file system crashed (my monitoring checks for crashed S3QL filesystems every minute). Of course this does not mean that the error would _not_ be in the auth token refresh code - auth token refreshes only happen on demand and a there might be a backend pool thread that did not refresh its auth token.

The auth token code of the Swift backend had no changes for some time (besides the ones in 3.6.0) and I cannot see how there a would be a way to exit S3QL without a traceback (no `sys.exit` anywhere and the backends do not use any trio calls or something else lowlevel)

I will have an eye on this but it might just have vanished or is so rare that is's unfeasible to debug.

**Comment by Nikratio** [comment] 2020-12-29 09:41
The issue of vanishing tracebacks is #227 - hopefully we can revisit this bug once that issue is resolved.

**Comment by Nikratio** [comment] 2020-12-30 12:03
I will close this for now since currently there is no good way to address this problem.

Once #227 is fixed (which will hopefully happen within the next week or so), could affected people please apply the patch and try to reproduce the problem? This time you should get a proper traceback that shows the root cause of the problem. If it happens, please open a new bug (including the full traceback).

Thank you for your patience and for taking the time to report this!

**Closed by Nikratio** 2020-12-30 12:03 UTC
